name: finder
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  flutter_localizations:
    sdk: flutter
  animate_do: ^3.3.4
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  country_code_picker: ^3.0.0
  retrofit_generator: ^8.1.0
  dartz: ^0.10.1
  image_picker: ^1.0.7
  get_it: ^7.6.7
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.0
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  intl: ^0.18.1
  connectivity_plus: ^6.0.3
  flutter_local_notifications: ^17.1.1
  rxdart: ^0.27.7






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1




  

flutter:
  uses-material-design: true


  assets:
    - asset/images/profile.png
    - asset/images/login.svg
    - asset/images/first_onBoarding_icon.svg
    - asset/images/second_onBoarding_icon.svg
    - asset/images/third_onBoarding_icon.svg
    - asset/images/camera.svg
    - asset/json/boyError.json
    - asset/json/empty.json
    - asset/json/emptySearch.json
    - asset/json/error.json
    - asset/json/loadFullScreen.json
    - asset/json/takePhoto.json
    - asset/images/missing_person.png
    - asset/images/find_person.png
    - asset/images/face.png
    - asset/json/success.json

    - asset/json/ai.json
    - asset/images/splash.svg
    - asset/images/app_logo.png
    - asset/json/no_match.json
    - asset/images/cloud.gif





  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: asset/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: asset/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: asset/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: asset/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: asset/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400

 
